### ISSUE TITLE
Relic keeps asking for remote configuration even after providing azure key vault options

### ISSUE THREAD

**Issue by AireshBhat** [sassoftware/relic#46]
Attached relic.yml file

```
---
# Tokens on which signing keys can be found. Each configured key refers to a token by name.
tokens:
  # Use keys stored in Azure Key Vault
  azurekv:
    type: azure
    # Optionally configure a service principal file
    #pin: service-principal.auth
    # Or use CLI authentication
    #pin: ""
    # Otherwise the environment will be used
# Keys that can be used for signing
keys:
  my_azure_key:
    token: azure
    # URL of key version resource. Must point to a key version, not a key.
    id: https://<VAULT_NAME>.vault.azure.net/certificates/<CERT_NAME>
    # Alternately, point to a certificate or certificate version. In this case
    # x509certificate may be omitted to load the cert from key vault as well.
    #id: https://example.vault.azure.net/certificates/my-azure-key
    # Same options as above: pgpcertificate, x509certificate, timestamp, roles
```

relic version 8.1.1 (9b4549bf3d344159b82672c20c698aadb124af47)
OS: Mac M1 Max

`relic remote sign --file target/x86_64-pc-windows-msvc/release/bundle/nsis/LIS-Desktop_0.1.1_x64-setup.exe --key azure --config relic.yml`
